Update patch set 3
Patch Set 3:

I'm getting the following on step 2 (make all):

[etcd]
make[1]: Entering directory '/root/multicloud-k8s/deployments/helm/v2/onap4k8s'
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "local" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 1 charts
Downloading common from repo http://127.0.0.1:8879
Deleting outdated charts
==> Linting etcd
[ERROR] Chart.yaml: apiVersion is required
[INFO] Chart.yaml: icon is recommended

Error: 1 chart(s) linted, 1 chart(s) failed
Makefile:54: recipe for target 'lint-etcd' failed
make[1]: *** [lint-etcd] Error 1
make[1]: Leaving directory '/root/multicloud-k8s/deployments/helm/v2/onap4k8s'
Makefile:44: recipe for target 'etcd' failed
make: *** [etcd] Error 2

Patch-set: 3
Reviewer: Gerrit User 693 <693@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>